defmodule Ltix.StorageAdapter do
  @moduledoc """
  Behaviour for host-app integration.

  Decouples the library from storage. The host app implements this behaviour
  to look up registrations, deployments, and manage nonces.
  """

  alias Ltix.{Deployment, Registration}

  @doc """
  Look up a platform registration by issuer and client_id.

  Called during OIDC login initiation
  [Sec §5.1.1.1](https://www.imsglobal.org/spec/security/v1p0/#step-1-third-party-initiated-login).
  The `client_id` parameter is optional — when not provided by the platform in
  the login request, the tool must be able to locate the registration by issuer alone.

  > [Core §4.1.3](https://www.imsglobal.org/spec/lti/v1p3/#client_id-login-parameter):
  > "The new optional parameter `client_id` specifies the client id for the
  > authorization server that should be used to authorize the subsequent LTI
  > message request."
  """
  @callback get_registration(issuer :: String.t(), client_id :: String.t() | nil) ::
              {:ok, Registration.t()} | {:error, :not_found}

  @doc """
  Look up a deployment by registration and deployment_id.

  Called during callback validation after the JWT deployment_id claim is
  extracted. The deployment_id is case-sensitive.

  > [Core §3.1.3](https://www.imsglobal.org/spec/lti/v1p3/#tool-deployment):
  > "Every message between the platform and tool MUST include the `deployment_id`
  > in addition to the `client_id`."
  """
  @callback get_deployment(registration :: Registration.t(), deployment_id :: String.t()) ::
              {:ok, Deployment.t()} | {:error, :not_found}

  @doc """
  Store a nonce during OIDC login initiation
  [Sec §5.1.1.2](https://www.imsglobal.org/spec/security/v1p0/#step-2-authentication-request).

  The nonce is generated by the library and must be persisted by the host app
  so that `validate_nonce/2` can verify it was issued by us and not replayed.
  """
  @callback store_nonce(nonce :: String.t(), registration :: Registration.t()) :: :ok

  @doc """
  Validate a nonce from the ID Token
  [Sec §5.1.3 step 9](https://www.imsglobal.org/spec/security/v1p0/#authentication-response-validation).

  The implementation MUST verify two things:
  1. The nonce was previously issued by this tool (matches a stored value)
  2. The nonce has not been used before (replay prevention)

  After successful validation, the nonce MUST be marked as consumed so it
  cannot be reused.
  """
  @callback validate_nonce(nonce :: String.t(), registration :: Registration.t()) ::
              :ok | {:error, :nonce_already_used | :nonce_not_found}
end
