defmodule Ltix.Integration.FullLaunchTest do
  use ExUnit.Case, async: true

  alias Ltix.{Deployment, LaunchClaims, LaunchContext, Registration}
  alias Ltix.Errors.Security
  alias Ltix.Test.{JWTHelper, TestStorageAdapter}

  @redirect_uri "https://tool.example.com/launch"

  setup do
    {private, public, kid} = JWTHelper.generate_rsa_key_pair()
    jwks = JWTHelper.build_jwks([public])

    {:ok, registration} =
      Registration.new(%{
        issuer: "https://platform.example.com",
        client_id: "tool-client-id",
        auth_endpoint: "https://platform.example.com/auth",
        jwks_uri: "https://platform.example.com/.well-known/jwks.json",
        tool_jwk: private
      })

    {:ok, deployment} = Deployment.new("deployment-001")

    {:ok, pid} =
      TestStorageAdapter.start_link(
        registrations: [registration],
        deployments: [deployment]
      )

    TestStorageAdapter.set_pid(pid)

    Req.Test.stub(Ltix.JWT.KeySet, fn conn ->
      conn
      |> Plug.Conn.put_resp_header("cache-control", "max-age=300")
      |> Req.Test.json(jwks)
    end)

    on_exit(fn ->
      Application.delete_env(:ltix, :storage_adapter)
      Application.delete_env(:ltix, :allow_anonymous)
    end)

    %{private: private, kid: kid, registration: registration, deployment: deployment}
  end

  # [Sec §5.1.1](https://www.imsglobal.org/spec/security/v1p0/#openid_connect_launch_flow)
  describe "complete launch flow [Sec §5.1.1]" do
    test "login → callback → LaunchContext", ctx do
      {:ok, login_result} = do_login()

      nonce = extract_nonce(login_result.redirect_uri)
      claims = JWTHelper.valid_lti_claims(%{"nonce" => nonce})
      id_token = JWTHelper.mint_id_token(claims, ctx.private, kid: ctx.kid)

      assert {:ok, %LaunchContext{} = launch} =
               Ltix.handle_callback(
                 %{"id_token" => id_token, "state" => login_result.state},
                 login_result.state,
                 storage_adapter: TestStorageAdapter,
                 req_options: req_options()
               )

      assert launch.registration == ctx.registration
      assert launch.deployment == ctx.deployment
      assert launch.claims.message_type == "LtiResourceLinkRequest"
      assert launch.claims.version == "1.3.0"
      assert launch.claims.target_link_uri == "https://tool.example.com/launch"
      assert launch.claims.subject == "user-12345"
    end

    test "nonce from login is bound to callback", ctx do
      {:ok, login_result} = do_login()

      # Use a different nonce than the one generated by login
      claims = JWTHelper.valid_lti_claims(%{"nonce" => "wrong-nonce"})
      id_token = JWTHelper.mint_id_token(claims, ctx.private, kid: ctx.kid)

      assert {:error, %Security.NonceNotFound{}} =
               Ltix.handle_callback(
                 %{"id_token" => id_token, "state" => login_result.state},
                 login_result.state,
                 storage_adapter: TestStorageAdapter,
                 req_options: req_options()
               )
    end

    test "state from login must match in callback", ctx do
      {:ok, login_result} = do_login()

      nonce = extract_nonce(login_result.redirect_uri)
      claims = JWTHelper.valid_lti_claims(%{"nonce" => nonce})
      id_token = JWTHelper.mint_id_token(claims, ctx.private, kid: ctx.kid)

      assert {:error, %Security.StateMismatch{}} =
               Ltix.handle_callback(
                 %{"id_token" => id_token, "state" => "wrong-state"},
                 login_result.state,
                 storage_adapter: TestStorageAdapter,
                 req_options: req_options()
               )
    end

    test "nonce cannot be replayed after successful callback", ctx do
      {:ok, login_result} = do_login()

      nonce = extract_nonce(login_result.redirect_uri)
      claims = JWTHelper.valid_lti_claims(%{"nonce" => nonce})
      id_token = JWTHelper.mint_id_token(claims, ctx.private, kid: ctx.kid)

      params = %{"id_token" => id_token, "state" => login_result.state}
      opts = [storage_adapter: TestStorageAdapter, req_options: req_options()]

      # First callback succeeds
      assert {:ok, %LaunchContext{}} =
               Ltix.handle_callback(params, login_result.state, opts)

      # Replay with same nonce fails
      assert {:error, %Security.NonceReused{}} =
               Ltix.handle_callback(params, login_result.state, opts)
    end
  end

  # [Cert §6.1.2](https://www.imsglobal.org/spec/lti/v1p3/cert/#valid-teacher-launches)
  describe "full flow with instructor [Cert §6.1.2]" do
    test "instructor launch with PII and context", ctx do
      {:ok, login_result} = do_login()

      nonce = extract_nonce(login_result.redirect_uri)

      claims =
        JWTHelper.valid_lti_claims(%{"nonce" => nonce})
        |> Map.put("name", "Jane Doe")
        |> Map.put("email", "instructor@example.com")
        |> Map.put("given_name", "Jane")
        |> Map.put("family_name", "Doe")
        |> put_lti_claim("context", %{
          "id" => "course-001",
          "label" => "CS101",
          "title" => "Intro to CS"
        })

      id_token = JWTHelper.mint_id_token(claims, ctx.private, kid: ctx.kid)

      assert {:ok, %LaunchContext{} = launch} =
               Ltix.handle_callback(
                 %{"id_token" => id_token, "state" => login_result.state},
                 login_result.state,
                 storage_adapter: TestStorageAdapter,
                 req_options: req_options()
               )

      assert LaunchClaims.Role.instructor?(launch.claims.roles)
      assert launch.claims.name == "Jane Doe"
      assert launch.claims.email == "instructor@example.com"
      assert launch.claims.context.id == "course-001"
      assert launch.claims.context.label == "CS101"
    end
  end

  # [Cert §6.1.3](https://www.imsglobal.org/spec/lti/v1p3/cert/#valid-student-launches)
  describe "full flow with student [Cert §6.1.3]" do
    test "student launch with PII and context", ctx do
      {:ok, login_result} = do_login()

      nonce = extract_nonce(login_result.redirect_uri)

      claims =
        JWTHelper.valid_lti_claims(%{"nonce" => nonce})
        |> put_lti_claim("roles", [
          "http://purl.imsglobal.org/vocab/lis/v2/membership#Learner"
        ])
        |> Map.put("name", "John Smith")
        |> Map.put("email", "student@example.com")
        |> put_lti_claim("context", %{
          "id" => "course-001",
          "label" => "CS101",
          "title" => "Intro to CS"
        })

      id_token = JWTHelper.mint_id_token(claims, ctx.private, kid: ctx.kid)

      assert {:ok, %LaunchContext{} = launch} =
               Ltix.handle_callback(
                 %{"id_token" => id_token, "state" => login_result.state},
                 login_result.state,
                 storage_adapter: TestStorageAdapter,
                 req_options: req_options()
               )

      assert LaunchClaims.Role.learner?(launch.claims.roles)
      assert launch.claims.name == "John Smith"
      assert launch.claims.email == "student@example.com"
      assert launch.claims.context.id == "course-001"
    end
  end

  # [Core §5.3.6.1](https://www.imsglobal.org/spec/lti/v1p3/#anonymous-launch-case)
  describe "full flow anonymous [Core §5.3.6.1]" do
    test "anonymous launch with allow_anonymous", ctx do
      {:ok, login_result} = do_login()

      nonce = extract_nonce(login_result.redirect_uri)

      claims =
        JWTHelper.valid_lti_claims(%{"nonce" => nonce})
        |> Map.delete("sub")

      id_token = JWTHelper.mint_id_token(claims, ctx.private, kid: ctx.kid)

      assert {:ok, %LaunchContext{} = launch} =
               Ltix.handle_callback(
                 %{"id_token" => id_token, "state" => login_result.state},
                 login_result.state,
                 storage_adapter: TestStorageAdapter,
                 allow_anonymous: true,
                 req_options: req_options()
               )

      assert launch.claims.subject == nil
    end
  end

  # -- Helpers --

  defp do_login do
    Ltix.handle_login(
      %{
        "iss" => "https://platform.example.com",
        "login_hint" => "user-hint-123",
        "target_link_uri" => "https://tool.example.com/launch"
      },
      @redirect_uri,
      storage_adapter: TestStorageAdapter
    )
  end

  defp extract_nonce(redirect_uri) do
    redirect_uri
    |> URI.parse()
    |> Map.get(:query)
    |> URI.decode_query()
    |> Map.fetch!("nonce")
  end

  defp req_options, do: [plug: {Req.Test, Ltix.JWT.KeySet}]

  defp put_lti_claim(claims, key, value) do
    Map.put(claims, "https://purl.imsglobal.org/spec/lti/claim/" <> key, value)
  end
end
